version: '3.3'
services:

  wxfdashboardsaio_influxdb:
    container_name: wxfdashboardsaio_influxdb
    env_file:
      - ./.env
    image: influxdb:1.8
    restart: always
    volumes:
      - /docker/weatherflow/influxdb:/var/lib/influxdb:rw
    ports:
      - 8086:8086
    networks:
      - grafana-external
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 30s
      timeout: 10s
      retries: 5

  wxfdashboardsaio-collector:
    container_name: wxfdashboardsaio-collector-08ce4425
    env_file:
      - ./.env
    restart: always
    depends_on:
      - "wxfdashboardsaio_influxdb"
    image: lux4rd0/weatherflow-collector:latest
    ports:
      - 50222:50222/udp
    networks:
      - grafana-external
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50222"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  grafana-external:
    external: true
    name: grafana-external
